### PR TITLE
Update run.php

### PR DESCRIPTION
**Pull request by cevn**
Prepending token with Bearer no longer seems to work for me.

### CODE REVIEW

**Comment by mikealmond** [comment]
In you `.env` file, does it include the `Bearer <token>` text?

**Comment by cevn** [comment]
It doesn't actually. 

Just HQ_BEARER_TOKEN=<The actual token>

**Comment by mikealmond** [comment]
You need to enter your actual bearer token coming from the app. You'll need to monitor the HTTP trafficing coming out of the app using a program like Fiddler or Charles Proxy.

**Comment by cevn** [comment]
Sorry, I mean to say it actually is populated with the token (think it got parsed out with Markdown). I have the actual token in there, without the word Bearer, but run.php only worked when I removed 'Bearer' like in the PR.

**Comment by Hulapopper** [comment]
I have no idea how to do this. I am on mac if that makes a difference.

**Pull request closed without merging**
