### PR TITLE
Added wikipedia as a search source.

### PR DESCRIPTION
**Pull request by MelonSmasher**
I've seen a slight improvement in results when using Wikipedia as an additional source to query.

### CODE REVIEW

**Comment by topper59** [comment]
Sweet, I found with Yahoo, Google and Wiki it took too long to get the answer. Replacing Yahoo with Wiki works best for me.

**Comment by dsf3449** [comment]
Thanks for this.  I also switched from the Canadian version of Google and Yahoo to the US versions and improved the search times slightly.

**Comment by Bowdoo95** [comment]
Couldn't anyone explain how to change google to the UK version of google, ive tried but everytime i change the version of google predictions.php throws a php fatal error?

**Comment by Tpixelminer** [comment]
@Bowdoo95 On line 70 in functions.php change the ca.google.com to `https://www.google.co.uk/search?q=` or change it to the US google like i have 
screen shot 2018-03-03 at 8 54 26 am

**Comment by Tpixelminer** [comment]
Also, does anybody know if there is any reason to keep Yahoo as a search source. What are you going to find with Yahoo that you are not going to find with Google?

**Comment by bburghall** [comment]
Could I replace Yahoo with wiki by simply changing the url? I would love help with this.

**Comment by MelonSmasher** [comment]
Closed this pull request. I received a cease and desists from HQ... they want me to take down this GitHub repo... I don't have any control over that HQ!

**Comment by dsf3449** [comment]
I'd imagine if you got one then all the contributors of this project received one.  Good luck!

**Pull request closed without merging**
